---
abstract: 'Multipurposes scenarios manager'
author:
  - 'L<Aleksei Melezhik|mailto:melezhik@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.17'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sparrow
no_index:
  directory:
    - inc
    - t
requires:
  Carton: 0
  JSON: 0
  Outthentic: 0.3.9
  Term::ANSIColor: '4.02'
  YAML: 0
  swat: 0.1.96
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/melezhik/sparrow
version: 0.2.52
